create table PROPERTY_FACILITY
(
    PROPERTY_ID            NUMBER not null
        primary key
        constraint PROPERTYFACILITY_PROPERTY_PROPERTY_ID_FK
            references PROPERTY,
    PARKING                VARCHAR2(1) default 0,
    LOBBY                  VARCHAR2(1) default 0,
    ELEVATOR               VARCHAR2(1) default 0,
    POOL                   VARCHAR2(1) default 0,
    SAUNA                  VARCHAR2(1) default 0,
    GYM                    VARCHAR2(1) default 0,
    BUILDING_GUARD         VARCHAR2(1) default 0,
    BALCONY                VARCHAR2(1) default 0,
    ROOFTOP_GARDEN         VARCHAR2(1) default 0,
    AIR_CONDITION          VARCHAR2(1) default 0,
    CONFERENCE_HALL        VARCHAR2(1) default 0,
    JACUZZI                VARCHAR2(1) default 0,
    CENTRAL_ANTENNA        VARCHAR2(1) default 0,
    REMOTE_CONTROLLED_DOOR VARCHAR2(1) default 0
)
/

INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (952, '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (955, '1', '1', '1', '1', '1', '0', '1', '0', '1', '1', '0', '1', '1', '0');
INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (252, '0', '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0');
INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (302, '0', '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0');
INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (303, '0', '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0');
INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (304, '0', '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0');
INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (352, '0', '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0');
INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (402, '0', '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0');
INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (403, '0', '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0');
INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (404, '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1');
INSERT INTO DB_PROJ.PROPERTY_FACILITY (PROPERTY_ID, PARKING, LOBBY, ELEVATOR, POOL, SAUNA, GYM, BUILDING_GUARD, BALCONY, ROOFTOP_GARDEN, AIR_CONDITION, CONFERENCE_HALL, JACUZZI, CENTRAL_ANTENNA, REMOTE_CONTROLLED_DOOR) VALUES (452, '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
